 
language: java

jdk:
  - openjdk9

cache:
  directories:
  - "$HOME/.m2/repository"

script:
  - mvn clean install
  # Comando para executar os plugins de relatório
  - mvn site
  # Comando para executar os testes
  - mvn clean test

